### ISSUE TITLE
Make dependency error

### ISSUE THREAD

**Issue by ptracton** [Martoni/spi2wb#2]
spi2wb$ make
sbt "runMain spi2wb.Spi2Wb"
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
[info] loading project definition from /home/ptracton/src/spi2wb/project
[info] loading settings for project root from build.sbt ...
[info] set current project to spi2wb (in build file:/home/ptracton/src/spi2wb/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.armadeus:wbplumbing_2.12:0.1-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/ptracton/.ivy2/localorg.armadeus/wbplumbing_2.12/0.1-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/armadeus/wbplumbing_2.12/0.1-SNAPSHOT/wbplumbing_2.12-0.1-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.armadeus:wbplumbing_2.12:0.1-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/ptracton/.ivy2/localorg.armadeus/wbplumbing_2.12/0.1-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/armadeus/wbplumbing_2.12/0.1-SNAPSHOT/wbplumbing_2.12-0.1-SNAPSHOT.pom
[error] Total time: 1 s, completed Jul 12, 2021, 9:48:18 PM
make: *** [Makefile:16: hdl] Error 1

I'm on Linux Mint 20.1
sbt 1.5.5 
Ubuntu Java 11.0.11

How do I get passed this dependency error?

**Comment by Martoni** [comment]
Hi @ptracton,
Thanks for this feedback.
You have to install [wbplumbing](https://github.com/Martoni/WbPlumbing) manually in local.

This should do the job: 

```
# if you want to install it in /opt for example
$ cd /opt
$ git clone https://github.com/Martoni/WbPlumbing.git
$ cd WbPlumbing
$ sbt "publishLocal"
```
I will improve the readme.

**Comment by ptracton** [comment]
That worked and I can build a simple version of the spi2wb.  

If you attempt to turn on BURST it fails.  This is a mode I am interested in trying out.

$ make DATASIZE=16 EXTADDR=1 BURST=1
sbt "runMain spi2wb.Spi2WbExt161"
[info] Updated file /home/ptracton/src/hardware/spi2wb/project/build.properties: set sbt.version to 1.5.5
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
[info] loading project definition from /home/ptracton/src/hardware/spi2wb/project
[info] loading settings for project root from build.sbt ...
[info] set current project to spi2wb (in build file:/home/ptracton/src/hardware/spi2wb/)
[info] compiling 1 Scala source to /home/ptracton/src/hardware/spi2wb/target/scala-2.12/classes ...
[info] running spi2wb.Spi2WbExt161 
[error] (run-main-0) java.lang.ClassNotFoundException: spi2wb.Spi2WbExt161
[error] java.lang.ClassNotFoundException: spi2wb.Spi2WbExt161
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 6 s, completed Jul 13, 2021, 6:45:27 PM
make: *** [Makefile:16: hdl] Error 1

**Comment by Martoni** [comment]
It's because you have to set variables before make I think :  
`$ DATASIZE=16 EXTADDR=1 BURST=1 make`

**Comment by ptracton** [comment]
Setting the variables in front of make worked.  I was able to generate.  Hopefully I will get to testing this module out soon and see if it will work for what I want to do.  Thanks!
